FROM registry.cn-hangzhou.aliyuncs.com/buyfakett/python:3.12.3-alpine3.19
WORKDIR /app
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk add --no-cache --virtual .build-deps gcc musl-dev libffi-dev openssl-dev bash \
    && apk add --no-cache libffi openssl subversion \
    && apk del .build-deps
ADD requirements.txt .
RUN pip3 install --no-cache-dir --upgrade pip setuptools wheel gunicorn -i https://pypi.tuna.tsinghua.edu.cn/simple \
    && pip3 install --no-cache-dir -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
ADD . .
RUN rm -f /etc/localtime && ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' > /etc/timezone
CMD uvicorn main:app --host 0.0.0.0 --port 8000
EXPOSE 8000
